#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PolishedToast_Xamarin.Resource.Drawable.ic_check_white_48dp = global::App.Resource.Drawable.ic_check_white_48dp;
			global::PolishedToast_Xamarin.Resource.Drawable.ic_clear_white_48dp = global::App.Resource.Drawable.ic_clear_white_48dp;
			global::PolishedToast_Xamarin.Resource.Drawable.ic_error_outline_white_48dp = global::App.Resource.Drawable.ic_error_outline_white_48dp;
			global::PolishedToast_Xamarin.Resource.Drawable.ic_info_outline_white_48dp = global::App.Resource.Drawable.ic_info_outline_white_48dp;
			global::PolishedToast_Xamarin.Resource.Drawable.toast_frame = global::App.Resource.Drawable.toast_frame;
			global::PolishedToast_Xamarin.Resource.Id.ImageViewToast = global::App.Resource.Id.ImageViewToast;
			global::PolishedToast_Xamarin.Resource.Id.TextViewToast = global::App.Resource.Id.TextViewToast;
			global::PolishedToast_Xamarin.Resource.Id.ToastLayout = global::App.Resource.Id.ToastLayout;
			global::PolishedToast_Xamarin.Resource.Layout.ToastLayout = global::App.Resource.Layout.ToastLayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_check_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_clear_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_error_outline_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_info_outline_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int toast_frame = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int ButtonAndroidDefault = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ButtonDefault = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int ButtonError = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ButtonInfo = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ButtonSuccess = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ButtonWarning = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int ImageViewToast = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int TextViewToast = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int ToastLayout = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ToastLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
