#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PolishedToast_Xamarin.Resource", IsApplication=false)]

namespace PolishedToast_Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_check_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_clear_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_error_outline_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_info_outline_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int toast_frame = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public static int ImageViewToast = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int TextViewToast = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int ToastLayout = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int ToastLayout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
